services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  nextjs-standalone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: nextjs-standalone
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "2095:3000"
    restart: unless-stopped
